version: "3.9"

services:
  backend:
    build: ./src/backend
    ports:
      - "4000:4000"
    container_name: backend

  frontend:
    build: ./src/frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    depends_on:
      - backend
    container_name: frontend