name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login a Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Build FRONTEND
      - name: Build frontend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/inventory-frontend:latest ./src/frontend

      # 4. Push FRONTEND
      - name: Push frontend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/inventory-frontend:latest

      # 5. Build BACKEND
      - name: Build backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/inventory-backend:latest ./src/backend

      # 6. Push BACKEND
      - name: Push backend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/inventory-backend:latest